### ISSUE TITLE
ID Site does not show a SAML button for Organizations that contain SAML Directories

### ISSUE THREAD

**Issue by dogeared** [stormpath/idsite-src#108]
__Note__: This may actually be an issue with AM, but the impact is manifesting in ID Site.

I have an Application with a couple of the Organizations:

![image](https://cloud.githubusercontent.com/assets/364562/12097072/a3f65bba-b2e7-11e5-9bf7-64f3973ae859.png)

The SAMLOrg has one SAML Directory in it:

![image](https://cloud.githubusercontent.com/assets/364562/12097093/bc5b2280-b2e7-11e5-9b78-cf287dab1264.png)

When I used my ID Site enabled application and get redirected to ID Site, this is what I see:

![image](https://cloud.githubusercontent.com/assets/364562/12097098/c4120e8a-b2e7-11e5-8cea-15ee5bbb4c47.png)

As soon as I add the SAML Directory into the list of Account Stores for the Application:

![image](https://cloud.githubusercontent.com/assets/364562/12097113/d7bcaae4-b2e7-11e5-86c4-5741cb645f38.png)

Then, I see the SAML button as expected:

![image](https://cloud.githubusercontent.com/assets/364562/12097120/e0a42f9c-b2e7-11e5-9e84-defb4c8efff7.png)

**Comment by dogeared** [comment]
Also, it looks like this issue extends to Social Directories too.

That is, if there's an Organization that has a Social Directory mapped as an Account Store, ID Site will not show the appropriate button for that Social Directory.

As soon as you map the Social Directory as an Account Store directly in the Application, ID Site will show the appropriate button for that Social Directory.

**Comment by robertjd** [comment]
Thanks for reporting this.  There is a fix that needs to happen in this application, the fix is that we must request the ID Site Model from the Organization resource (not the Application) in these situations.  I've just released that fix as version 0.5.0 of [stormpath.js](https://github.com/stormpath/stormpath.js), which is a depended on by this library and is the library which does the resolution of the ID Site Model.

However, we need to make a fix on the Stormpath API in order to allow the Organization's ID Site Model to be accessible from ID Site.  That's being tracked as AM-2965.

Once that issue is resolved, I will update this application to depend on stormpath.js@0.5.0
